# Generated by Django 5.0.6 on 2024-05-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип кузова')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Назва авто')),
                ('year', models.IntegerField(verbose_name='Рік випуску')),
                ('volume', models.FloatField(verbose_name="Об'єм двигуна")),
                ('power', models.IntegerField(verbose_name='Потужність(к.с)')),
                ('sing_of_car', models.CharField(max_length=255, verbose_name='Номер авто')),
                ('is_fixing', models.BooleanField(default=False, verbose_name='В ремонті:')),
                ('is_used', models.BooleanField(default=False, verbose_name='Використовується:')),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bodytype', verbose_name='Тип кузова')),
            ],
        ),
    ]
