# Generated by Django 5.0.6 on 2024-05-19 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 22, 54, 20, 287461, tzinfo=datetime.timezone.utc)),
        ),
    ]
